export const ADD_TO_BASKET = "ADD_TO_BASKET";
export const DELETE_FROM_BASKET = "DELETE_FROM_BASKET";

export const FETCH_SESSION_STATE = "FETCH_SESSION_STATE";
export const FETCH_SESSION_STATE_SUCCESS = "FETCH_SESSION_STATE_SUCCESS";
export const FETCH_SESSION_STATE_ERROR = "FETCH_SESSION_STATE_ERROR";

export const FETCH_PRODUCTS = "FETCH_PRODUCTS";
export const FETCH_PRODUCTS_SUCCESS = "FETCH_PRODUCTS_SUCCESS";
export const FETCH_PRODUCTS_ERROR = "FETCH_PRODUCTS_ERROR";

export const SET_VISIBILITY_FILTER = "SET_VISIBILITY_FILTER";
