export const ADD_TO_BASKET = "ADD_TO_BASKET";
export const REMOVE_FROM_BASKET = "REMOVE_FROM_BASKET";
export const REMOVE_ALL_FROM_BASKET = "REMOVE_ALL_FROM_BASKET";

export const SET_VISIBILITY_FILTER = "FILTER_LIST";
